### Loading the dataset
The news dataset is a text dataset with folders as labels and the files inside as the actual data.
So, i have loaded the data from those files into 2 python lists: a document, with the actual text content and a label, with the label for that particular document.

In [ ]:
import os

def load_20newsgroups(data_dir):
    """
    This function will extract all the data in sub directories into python lists for future use.
    """
    documents = []
    labels = []

    for category in os.listdir(data_dir):
        category_path = os.path.join(data_dir, category)

        if not os.path.isdir(category_path):
            continue

        for filename in os.listdir(category_path):
            file_path = os.path.join(category_path, filename)

            try:
                with open(file_path, "r", encoding="latin1") as f:
                    text = f.read()

                documents.append(text)
                labels.append(category)

            except Exception as e:
                print(f"Error reading {file_path}: {e}")

    return documents, labels

In [2]:
data_dir = "data/20_newsgroups"

documents, labels = load_20newsgroups(data_dir)

print("Total documents:", len(documents))
print("Example label:", labels[0])
print("Example text:", documents[0][:500])

Total documents: 19997
Example label: alt.atheism
Example text: Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:120737 alt.atheism:53341 talk.religion.misc:83726
Path: cantaloupe.srv.cs.cmu.edu!magnesium.club.cc.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!pacific.mps.ohio-state.edu!zaphod.mps.ohio-state.edu!usc!sol.ctr.columbia.edu!ira.uka.de!Germany.EU.net!thoth.mchp.sni.de!horus.ap.mchp.sni.de!D012S658!frank
From: frank@D012S658.uucp (Frank O'Dwyer)
Newsgroups: talk.abortion,alt.atheism,talk.religion.misc
Subject: Re: After 2000 years, can we say that Christ

### Storing dataset in structured format
Using data from files is not so convenient so I have stored it in a pandas dataframe and exported it in csv format for convenient future use.

In [ ]:
import pandas as pd

def create_dataframe(documents, labels):
    """
    Create a pandas dataframe from the document text and labels available
    """

    df = pd.DataFrame({
        "text": documents,
        "category": labels
    })

    return df

In [5]:
df = create_dataframe(documents, labels)
df.head()

                                                text     category
0  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  alt.atheism
1  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...  alt.atheism
2  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
3  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism

In [6]:
#export the dataset to csv format for future use
df.to_csv("newsgroups_raw.csv", index=False)

In [7]:
df["doc_id"] = range(len(df))
df.head()

                                                text     category  doc_id
0  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  alt.atheism       0
1  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...  alt.atheism       1
2  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism       2
3  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism       3
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism       4

In [8]:
df["category"].value_counts()

category
alt.atheism                 1000
comp.graphics               1000
comp.os.ms-windows.misc     1000
comp.sys.ibm.pc.hardware    1000
comp.sys.mac.hardware       1000
comp.windows.x              1000
misc.forsale                1000
rec.autos                   1000
rec.motorcycles             1000
rec.sport.baseball          1000
rec.sport.hockey            1000
sci.crypt                   1000
sci.electronics             1000
sci.med                     1000
sci.space                   1000
talk.politics.guns          1000
talk.politics.mideast       1000
talk.politics.misc          1000
talk.religion.misc          1000
soc.religion.christian       997
Name: count, dtype: int64